version: "3.7"

networks:
  helpmeifyoucan:

services:

  backend:
    build: .
    container_name: helpmeifyoucan-backend
    environment: 
      - PROFILE=production
    networks: 
      - helpmeifyoucan
    depends_on: 
      - database
  
  database:
    image: mongo
    container_name: helpmeifyoucan-db
    volumes:
      - ./volumes/mongo:/data/db
    networks: 
      - helpmeifyoucan
    ports: 
      - 27017:27017

  frontend:
    build:
      context: https://github.com/MrJoxus/HelpMeIfYouCan-Frontend.git
      args:
        BASE_URL: localhost
        BASE_PORT: 3030
        BACKEND_URL: backend
        BACKEND_PORT: 8080
        GOOGLE_API_KEY: 
    networks:
      - helpmeifyoucan
    ports:
      - 3030:3030


