spring:
  profiles: production
  main:
    banner-mode: off
    lazy-initialization: false
server:
  port: 8080
  error:
    include-stacktrace: always
logging:
  level:
    .: error
    org.springframework:
      .: INFO
      security.web.FilterChainProxy: INFO
    org.zalando.logbook: TRACE
    
    org.mongodb.driver:
      .: INFO
      cluster: OFF
    de.helpmeifyoucan:
      .: DEBUG
database:
  protocol: mongodb
  host: database
  name: helpmeifyoucan
jwt:
  secret: ${random.value}
  expiration: 864000000
logbook:
  format.style: http
  filter.enabled: true
  secure-filter.enabled: false
  strategy: default
  obfuscate:
    headers:
      - Authorization
    parameters:
      - password
      - currentPassword