spring:
  profiles: local
  main:
    banner-mode: off
    lazy-initialization: false
server:
  port: 8080
logging:
  level:
    .: error
    org.springframework: INFO
    org.zalando.logbook: TRACE
    org.mongodb.driver:
      .: INFO
      cluster: OFF
database:
  protocol: mongodb
  host: "localhost"
  name: helpmeifyoucan
jwt:
  secret: ujaerahgh4ohqui6OJ8ta9aughaitha5ohtookaem1eeH3doh9hei0Oovu8kai1H
  expiration: 864000000
logbook:
  format.style: http
  filter.enabled: true
  secure-filter.enabled: false
  strategy: default
  obfuscate:
    headers:
      - Authorization
    parameters:
      - password
      - currentPassword
