spring:
  profiles: development
  main:
    banner-mode: console
    lazy-initialization: false
server:
  port: 8080
  error:
    include-stacktrace: always
logging:
  level:
    .: error
    org.springframework: INFO
    org.zalando.logbook: TRACE
    org.mongodb.driver:
      .: INFO
      cluster: OFF
    de.helpmeifyoucan:
      .: DEBUG
database:
  protocol: mongodb
  host: localhost
  name: helpmeifyoucan
jwt:
  secret: me9ohjeicheich7abuchie7eiK9reeTaek3Oowaeyie1aip8keepai7paivi1Eig
  expiration: 864000000
logbook:
  format.style: http
  filter.enabled: true
  secure-filter.enabled: false
  strategy: default
  obfuscate:
    headers:
      - Authorization
    parameters:
      - password
      - currentPassword