spring:
  profiles: development
  main:
    banner-mode: console
    lazy-initialization: false
server:
  port: 8080
logging:
  level:
    .: error
    org.springframework: INFO
    org.zalando.logbook: TRACE
    org.apache.tomcat: INFO
    org.mongodb.driver:
      .: INFO
      cluster: OFF
database:
  protocol: mongodb+srv
  host: "helpme-1rsgf.mongodb.net/test?retryWrites=true&w=majority"
  name: helpmeifyoucan
  user: dbUser
  password: ${DATABASE_PASSWORD}
jwt:
  secret: yeipu7koo6ceez5quieDeenooxeep9wu
  expiration: 864000000
logbook:
  format.style: http
  filter.enabled: true
  secure-filter.enabled: false
  strategy: default
  obfuscate:
    headers:
      - Authorization
    parameters:
      - password
      - currentPassword
